// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/jmvargas/go-kit-example/catalog/pkg/endpoint"
	pb "github.com/jmvargas/go-kit-example/catalog/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	get  grpc.Handler
	list grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.CatalogServer {
	return &grpcServer{
		get:  makeGetHandler(endpoints, options["Get"]),
		list: makeListHandler(endpoints, options["List"]),
	}
}
